pserver: tcp_pthread_server.cpp protocol_parser.hpp protocol_parser.cpp
	g++ -g tcp_pthread_server.cpp protocol_parser.cpp -lpthread -lwiringPi -lrt -o pserver
server: server.cpp
	g++ -g server.cpp -o server -lwiringPi